export const technologies = [
    { lang: "Reactjs", icon: "/icons/react.svg", hide: true },
    { lang: "Nextjs", icon: "/icons/nextjs-original.svg" },
    { lang: "Javascript", icon: "/icons/javascript-original.svg" },
    { lang: "Nodejs", icon: "/icons/nodejs-original.svg" },
    { lang: "Express", icon: "/icons/express-original.svg" },
    { lang: "Python", icon: "/icons/python-original.svg" },
    { lang: "Django", icon: "/icons/django-plain.svg" },
    { lang: "Flask", icon: "/icons/flask.svg" },
    { lang: "API", icon: "/icons/api-icon.svg" },
    { lang: "HTML", icon: "/icons/html5-original.svg" },
    { lang: "CSS3", icon: "/icons/css3-original.svg" },
    { lang: "Tailwind", icon: "/icons/tailwindcss-original.svg" },
    { lang: "PostgreSQL", icon: "/icons/postgresql-original.svg" },
    { lang: "MySQL", icon: "/icons/mysql-original.svg" },
    { lang: "phpmyadmin", icon: "/icons/phpmyadmin.svg" },
    { lang: "Linux", icon: "/icons/linux-original.svg" },
    { lang: "Odoo", icon: "/icons/odoo.svg", hide: true },
    { lang: "php", icon: "/icons/php.svg", hide: true },
    { lang: "Laravel", icon: "/icons/laravel.svg", hide: true },
    { lang: "Wordpress", icon: "/icons/wordpress.svg", hide: true },
    { lang: "Nginx", icon: "/icons/nginx-original.svg" },
    { lang: "Git", icon: "/icons/git-original.svg" },
    { lang: "Docker", icon: "/icons/docker-original.svg" },
    { lang: "DigitalOcean", icon: "/icons/digitalocean-original.svg" },
    { lang: "Jira", icon: "/icons/jira-original.svg" },
    { lang: "Postman", icon: "/icons/postman-original.svg" },
    { lang: "slack", icon: "/icons/slack-original.svg" },
];